[package]
name = "nvim-rpc"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rmp = "0.8.14"
rmpv = "1.3.0"
serde = { version = "1.0.203", features = ["derive"] }

[build-dependencies]
handlebars = "5.1.2"
rmpv = "1.3.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
