[package]
name = "genapi"
version = "0.1.2"
edition = "2021"

[dependencies]
handlebars = "5.1.2"
regex = "1.10.5"
rmpv = "1.3.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
