[package]
name = "genapi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
handlebars = "5.1.2"
rmpv = "1.3.0"
serde = { version = "1.0.203", features = ["derive"] }
